I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/labeljump.rpy", line 74, in script
    return start
  File "game/labeljump.rpy", line 74, in <module>
    return start
NameError: name 'start' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/labeljump.rpy", line 74, in script
    return start
  File "E:\renpy-8.2.0-sdk\renpy\ast.py", line 1481, in execute
    renpy.store._return = renpy.python.py_eval(self.expression)
  File "E:\renpy-8.2.0-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "E:\renpy-8.2.0-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/labeljump.rpy", line 74, in <module>
    return start
NameError: name 'start' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.2.0.24012702
International Serious Game 1.0
Thu Mar  7 16:23:18 2024
